---
# Default yolo configuration
# Override any of these in your user or project config

env:
  - CLAUDE_CODE_OAUTH_TOKEN
  - CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS

images:
  - name: default
    extras:
      - name: apt
        packages:
          - fzf
          - gh
          - less
          - man-db
          - shellcheck
          - zsh
      - name: git-delta
        version: "0.18.2"
      - name: python
        version: "3.12"
